name: CI/CD para Site Estático

on:
  push:
    branches:
      - main   # dispara quando houver push na branch main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Validação básica de HTML, CSS e JS (lint)
      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v6
        with:
          root: "."

      - name: Validar CSS
        run: |
          npx stylelint "**/*.css"

      - name: Validar JavaScript
        run: |
          npx eslint "**/*.js"

      # 3. Deploy no GitHub Pages
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # aqui você define a pasta do site (ex.: ./public ou ./dist)
